#import("../../../src/abla-mvc.ab")
#import("../models/counter.ab")
#import("../views/counter_view.ab")
#import("../controllers/counter_controller.ab")
#import("../controllers/client_counter_controller.ab")
#import("../views/auth_view.ab")

fun main: int {
    val login = loginView(LoginViewModel("")).render()
    val dashboard = dashboardView(DashboardViewModel(
        "admin",
        "query",
        0
    )).render()
    if (login.size > 1000 && dashboard.size > 1000) 0 else 1
}
