import "abla/http"
import "http.ab"

fun mvcStylesheetResponse(contents: string): HttpResponse = mvcPublicCache(
    HttpResponse(
        200,
        [HttpHeader("Content-Type", "text/css; charset=utf-8")],
        contents
    ),
    300
)

fun mvcWasmResponse(contents: string): HttpResponse = mvcPublicCache(
    HttpResponse(
        200,
        [HttpHeader("Content-Type", "application/wasm")],
        contents
    ),
    300
)
